language: node_js
node_js:
  - 0.1

env:
  global:
    - BROWSER_PROVIDER_READY_FILE=/tmp/sauce-connect-ready
    - LOGS_DIR=/tmp/watchtower-build/logs
    - SAUCE_USERNAME=angular-ci
    - SAUCE_ACCESS_KEY=9b988f434ff8-fbca-8aa4-4ae3-35442987

before_script:
  - mkdir -p $LOGS_DIR
  - npm install karma-sauce-launcher

script:
  - ./lib/travis/build.sh

after_script:
  - ./lib/travis/print_logs.sh
