#pragma once

#include <stdbool.h>

typedef enum {
  NONE = 0,
  ERROR_COMPILER_ADDRESS_OF_FUNCTION,
  ERROR_COMPILER_ADDRESS_OF_NAME,
  ERROR_COMPILER_ALLOCATION_FAILURE,
  ERROR_COMPILER_EXPECTED_LIST,
  ERROR_COMPILER_EXPECTED_NAME_NODE,
  ERROR_COMPILER_EXPECTED_NAME_OR_LIST,
  ERROR_COMPILER_EXPECTED_VECTOR_OR_LIST,
  ERROR_COMPILER_FN_CALL_GIVEN_NON_LIST,
  ERROR_COMPILER_GENES_REMAINING_AFTER_ASSIGNING,
  ERROR_COMPILER_INCOMPATIBLE_GENE,
  ERROR_COMPILER_MAX_TOP_LEVEL_FUNCTIONS,
  ERROR_COMPILER_NO_STEP_PARAMETERS_FOR_LOOP,
  ERROR_COMPILER_NO_TO_OR_UPTO_PARAMETERS_FOR_LOOP,
  ERROR_COMPILER_NULL_GENE,
  ERROR_COMPILER_PREAMBLE_CODE_SIZE,
  ERROR_COMPILER_PROGRAM_REACHED_MAX_SIZE,
  ERROR_COMPILER_UNABLE_TO_CORRECT_FN_ADDR,
  ERROR_COMPILER_UNABLE_TO_FIND_FN_INFO,
  ERROR_COMPILER_UNABLE_TO_FIND_VARIABLE,
  ERROR_COMPILER_UNKNOWN_MAPPING_FOR_NAME,
  ERROR_COMPILER_UNKNOWN_MEMORY_SEGMENT_TYPE,
  ERROR_NULL_NODE,
  ERROR_PARSE,
  ERROR_PARSE_END_OF_INPUT,
  ERROR_PARSE_EXPECTED_END_OF_LIST,
  ERROR_PARSE_EXPECTED_END_OF_VECTOR,
  ERROR_PARSE_NON_MUTABLE_NODE,
  ERROR_PARSE_NULL_INPUT,
  ERROR_WLUT_ADD_FAILED,
  ERROR_WLUT_LOOKUP_FAILED,
  ERROR_GENERAL,
} sen_error;

bool is_error(sen_error error);
