[package]
name = "seni-gui"
version = "0.1.0"
authors = ["Inderjit Gill <email@indy.io>"]
edition = "2018"
license = "GPL-3.0+"

[dependencies]
imgui = "0.0.22"
sdl2 = "0.32.1"
imgui-sdl2 = "0.5"
gl = "0.10.0"
imgui-opengl-renderer = "0.4"
