[package]
name = "server"
version = "4.1.0"
authors = ["Inderjit Gill <email@indy.io>"]
edition = "2018"

[dependencies]
clap = "2.32.0"
env_logger = "0.5.4"
actix = "0.7"
actix-web = "^0.7"
# json
serde = "1.0.32"
serde_derive = "1.0.32"
serde_json = "1.0.32"
