[package]
name = "theme-builder"
version = "0.1.0"
authors = ["Inderjit Gill <email@indy.io>"]
edition = "2018"
license = "AGPL-3.0"

[dependencies]
fs_extra = "1.1.0"

[dependencies.sass-rs]
git = "https://github.com/compass-rs/sass-rs"
rev = "967492429c891ea80f9aeef9cc90fea3e59d3453"
